name: Build Status

on: [push, pull_request]

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.100" # SDK Version to use.
      - run: dotnet build
      - run: dotnet test
