name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: Lint files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Markdown Linting Action
        uses: avto-dev/markdown-lint@v1
        with:
          args: '*.md'
  build_and_test:
    needs: lint
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1.7.0
        with:
          dotnet-version: "3.1.100" # SDK Version to use.
      - run: dotnet build
      - run: dotnet test
